version: "3.8"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: StepByStep
  graphql:
    build: .
    ports:
      - 4000:4000
    environment:
      POSTGRES_HOST: postgres
      JWT_SECRET: random
    depends_on:
      - postgres
